### ISSUE TITLE
[BUG] Sometimes inventories works wrong for MTF and CI

### ISSUE THREAD

**Issue by iojforever** [steven4547466/Advanced-Subclassing-Redux#17]
My config is:
```
name: Text

affects_roles:
  ChaosConscript: 1

string_options:
  GotClassMessage: Text
  HelpMessage: Text
  CustomInfo: Text

int_options: # also supports "MaxArmor" and "ArmorOnSpawn" currently, however this will decay, so they're pretty useless, may as well just give them some body armor in spawn_items.
  MaxHealth: 100
  HealthOnSpawn: 100
  MaxAlive: 1

bool_options:
  RemoveDefaultSpawnItems: true
  RemoveDefaultSpawnAmmo: true

spawn_items:
  - GunAK: 100
  - KeycardChaosInsurgency: 100
  - KeycardContainmentEngineer: 100
  - Radio: 100
  - ArmorCombat: 100

spawn_ammo:
  Nato762: 120
  ```
  But wait. There is more:
  
![image](https://user-images.githubusercontent.com/81348376/177172514-165824c5-4365-428e-b5d2-6e15473b2e1b.png)
 
 Thats their standart inventory
