### ISSUE TITLE
[enhancement] Port or remake effects for classes on different events

### ISSUE THREAD

**Issue by iojforever** [steven4547466/Advanced-Subclassing-Redux#8]
### If you dont interested in my opinion, please ignore this text and first read the paragraph **Config Variation Example**
Since **old config variation** included alot of **unnecessary parameters** it was really big and kinda kinky, so that could be a headache to maintain such an option:
```
float_options:
  OnHitDisabledChance: 10
  OnHitDisabledDuration: 40
  OnSpawnHemorrhageChance: 100
  OnSpawnHemorrhageDuration: 200
  OnDamagedEnsnaredChance: 50
  OnDamagedEnsnaredDuration: 4
  
on_hit_effects:
- Disabled

on_spawn_effects:
- Hemorrhage

on_damaged_effects:
  E11StandardRifle:
  - Ensnared
  Logicer:
  - Ensnared
  Mp7:
  - Ensnared
  P90:
  - Ensnared
  Usp:
  - Ensnared
  Com15:
  - Ensnared
```
I think this is unnecessary for **REDUX** version, so maybe just remove those parts with effects being set up in config and use this example config instead:

### Config Variation Example
```
float_options:
  GiveAmnesiaChance: 70
  GiveAmnesiaDuration: 2
  GainAmnesiaChance: 0
  GainAmnesiaDuration: 0
  SpawnAmnesiaChance: 0
  SpawnAmnesiaDuration: 0
  
effects_modification:
  - Amnesia
  - Disabled
```
As presented here, Disabled effects is not configured so if it even shows up in config it will not work, since there is no configuration for it. But, since Amnesia is configured for being given after attack or being gain after damage taken, it will work correctly. I was inspired by your AHP system rework.
**If that possible, of course. Thank you.**
